spring.application.name=OAuth-Project

spring.security.user.name=Kashi
spring.security.user.password=kashi123

#oauth for github app
spring.security.oauth2.client.registration.github.client-id={clientId}
spring.security.oauth2.client.registration.github.client-secret={clientSecret}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

#oauth for google app
spring.security.oauth2.client.registration.google.client-id={clientId}
spring.security.oauth2.client.registration.google.client-secret={clientSecret}
